[build]
  publish = "dist/"
  command = "npm run build:ci"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = "public, max-age=60, stale-while-revalidate=120, stale-if-error=600"

[[headers]]
  for = "/*.js"
  [headers.values]
      cache-control = "public, max-age=6048000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
      cache-control = "public, max-age=6048000, immutable"

[[redirects]]
  from = "https://redos-detector.netlify.app/*"
  to = "https://redosdetector.com/:splat"
  status = 301
  force = true
